import "./globals.css";
import Header from "../components/layout/Header";
import { AppProvider } from "@/components/AppContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Trendy Tail",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
